name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync backend files to /var/www
        run: |
          rsync -av --delete ./shahrpitaj.ir-backend/ /var/www/shahrpitaj.ir-backend/

      - name: Install backend dependencies
        run: |
          cd /var/www/shahrpitaj.ir-backend
          npm install --production

      - name: Restart backend with PM2
        run: |
          cd /var/www/shahrpitaj.ir-backend
          pm2 restart shahrpitaj-backend || pm2 start app.js --name shahrpitaj-backend
          pm2 save
