name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Install Dependencies
        run: npm i

      - name: Build
        continue-on-error: true
        run: npm run build

      - name: Delete Previous Process Silently
        continue-on-error: true
        run: pm2 delete shahrpitaj || true

      - name: Start a New Process
        run: pm2 start build/app.js --name shahrpitaj

      - name: Save Current Process List
        run: pm2 save